logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
server:
    error:
        include-binding-errors: always
        include-message: always
    port: 8092
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        platform: h2
        url: jdbc:h2:mem:customerDB
        username: sa
    h2:
        console:
            enabled: true
            settings:
                trace: false
                web-allow-others: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: false
                show_sql: true
                use_sql_comments: false
        show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
management: #actuator
  endpoints:
    web:
      exposure:
        include: "*"